---
title: "lab5"
author: "Быков Игнорь"
date: '19 декабря 2018 г '
output: html_document
---


knitr::opts_chunk$set(echo = TRUE)
library(dplyr)



data = read.csv("https://raw.githubusercontent.com/InfantLab/NotebookDemos/master/diet.csv",row.names=1)
summary(data)
colnames(data) <- c("gender", "age", "height", "initial.weight", 
                    "diet.type", "final.weight")
data$diet.type <- factor(c("A", "B", "C")[data$diet.type])
#Добавим новую колонку - Похудение
data$weight.loss = data$initial.weight - data$final.weight
#Проанализиуем есть ли различия по типам диет
boxplot(weight.loss~diet.type,data=data,col="light gray",
        ylab = "Weight loss (kg)", xlab = "Diet type")
abline(h=0,col="green")
#проверим сбалансированные ли данные
table(data$diet.type)

#График групповых средних
library(gplots) #библиотека устанавлевается с помощью install.packages
plotmeans(weight.loss ~ diet.type, data=data)
aggregate(data$weight.loss, by = list(data$diet.type), FUN=sd)
#Для подгонки ANOVA модели используем функцию aov, частный случай линейной модели lm
#тест на межгрупповые различия
fit <- aov(weight.loss ~ diet.type, data=data)
summary(fit)
#попарные различия между средними значениями для всех групп
TukeyHSD(fit)
#Tukey honest significant differences test)
library(multcomp)
par(mar=c(5,4,6,2))
tuk <- glht(fit, linfct=mcp(diet.type="Tukey"))
plot(cld(tuk, level=.05),col="lightgrey")

#Задание
plot(data$weight.loss ~ data$diet.type)
par(mfrow=c(1,5))
hist(data$age, main = "возвраст")
hist(data$height, main = "рост")
hist(data$initial.weight, main = "вес до диеты")
hist(data$final.weight, main = "вес после")
hist(data$weight.loss, main = "похудел на")

data <- data %>%  filter(weight.loss >= 0 & weight.loss <= 8) 
#Проанализиуем есть ли различия по типам диет
boxplot(weight.loss~diet.type,data=data,col="light gray",
        ylab = "Weight loss (kg)", xlab = "Diet type")
abline(h=0,col="green")
#проверим сбалансированные ли данные
table(data$diet.type)

#График групповых средних
library(gplots) #библиотека устанавлевается с помощью install.packages
plotmeans(weight.loss ~ diet.type, data=data)
aggregate(data$weight.loss, by = list(data$diet.type), FUN=sd)
#Для подгонки ANOVA модели используем функцию aov, частный случай линейной модели lm
#тест на межгрупповые различия
fit <- aov(weight.loss ~ diet.type, data=data)
summary(fit)
#попарные различия между средними значениями для всех групп
TukeyHSD(fit)
#Tukey honest significant differences test)
library(multcomp)
par(mar=c(5,4,6,2))
tuk <- glht(fit, linfct=mcp(diet.type="Tukey"))
plot(cld(tuk, level=.05),col="lightgrey")

# Задания с листочка
data <- data %>% filter(!is.na(gender))
data$gender <- factor( c('Female', 'Male')[as.ordered(data$gender)] )
summary(data)
# Проверим, сбалансированы ли данные
table(data$gender)
# Проанализируем, есть ли различия
boxplot(weight.loss~gender,data=data,col="light gray",
        ylab = "Weight loss (kg)", xlab = "Diet type")
abline(h=0,col="green")
# График групповых средних
plotmeans(weight.loss ~ gender, data=data)
aggregate(data$weight.loss, by = list(data$gender), FUN=sd)
# Для подгонки ANOVA модели используем функцию aov, частный случай линейной модели lm тест на межгрупповые различия
fit <- aov(weight.loss ~ gender, data=data)
summary(fit)
# Попарные различия между средними значениями для всех групп
THSD <- TukeyHSD(fit)
THSD
# Tukey honest significant differences test)
par(mar=c(5,4,6,2))
tuk <- glht(fit, linfct=mcp(gender="Tukey"))
plot(cld(tuk, level=.05),col="lightgrey")

